= Learning JS & NodeJS
This repo is an experiment to learn more about NodeJS, related libraries & automation tools.

== Change Log
- *Each folder should have a readme.adoc file explaining what it's purpose.*



== Essentials:
----
sudo apt install -y gcc-c++ make
----

== Useful Commands
- List global packages `npm list -g --depth 0`
- Vulnerability audit and fix `npm audit` and `npm audit fix`
- Find reverse package dependency `npm ls PackageName`

== Folder Structure with NodeJS and Webpack

- *bin/* :
- *build/* : development & production webpack config
- *config/* :
** *config/inded.js* : main project config file.
- *src/* : This is where most of the application code will go. Structure of content depends on the developer & typ of project.
- *static/* : Any assets that needs to be only copied  and doesnt need to be process by webpack.
- *test/* :
- *node_modules/*



== Installing NodeJS & NPM

.nvm
https://github.com/nvm-sh/nvm#installation-and-update
----
nvm ls
nvm install 10
nvm use 10

----
=== Fixing Node installation issues (Tested on Centos)
----
/bin/rm -rf /var/cache/yum
/usr/bin/yum remove -y nodejs
/bin/rm /etc/yum.repos.d/nodesource*
/usr/bin/yum clean all
/usr/bin/curl --silent --location https://rpm.nodesource.com/setup_8.x | bash -
----
as shown on:
- https://github.com/nodesource/distributions/issues/486




